library(R6)
Queue <- R6Class("Queue",
                 public = list(
                   initialize = function(...) {
                     for (item in list(...)) {
                       self$add(item)
                     }
                   },
                   add = function(x) {
                     private$queue <- c(private$queue, list(x))
                     invisible(self)
                   },
                   remove = function() {
                     if (private$length() == 0) return(NULL)
                     # Can use private$queue for explicit access
                     head <- private$queue[[1]]
                     private$queue <- private$queue[-1]
                     head
                   }
                 ),
                 private = list(
                   queue = list(),
                   length = function() base::length(private$queue)
                 )
)

CountingQueue <- R6Class("CountingQueue",
                         inherit = Queue,
                         public = list(
                           add = function(x) {
                             private$total <<- private$total + 1
                             super$add(x)
                           },
                           get_total = function() private$total
                         ),
                         private = list(
                           total = 0
                         )
)

R62S3("Queue") # Generated by naming the R6ClassGenerator
R62S3(CountingQueue) # Generated by giving the R6ClassGenerator
q <- Queue$new(5, 6, "foo")
add(q,"Something") # Add() via dispatch. Works with additional parameters.
q$.__enclos_env__$private$queue
remove(q) # Remove() via dispatch
remove(q)
q$.__enclos_env__$private$queue
cq <- CountingQueue$new("x","y")
get_total(cq)
add(cq,"z")
get_total(cq)
remove(cq) # Calls to the parent class work via dispatch without needing to define a new method
cq$.__enclos_env__$private$queue
